server:
  port: 7075
spring:
  profiles:
    active: local
  application:
    name: '@project.artifactId@'

#DataSource
  datasource:
    url: jdbc:h2:file:./data/bookDB
    driver-class-name: org.h2.Driver
    username: admin
    password: books
  jpa:
    defer-datasource-initialization: true
    show-sql : false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
jwt:
  secret : book-store



